### PR TITLE
Integration test for filtering rows using RegEx

### LINKED ISSUE #2008: Hbase FilterList as MUST_PASS_ONE with two RegexStringComparator RowFilters returns everything
As per https://stackoverflow.com/questions/53395833/hbase-filterlist-as-must-pass-one-with-two-rowfilters-returns-everything 

I have a column family called odds_api with the number of rows with the rowkey: /bt=??/bm=??/mk=??/se=??:

```
/bt=1/bm=MN/mk=344/se=23394/odds_api
/bt=1/bm=BY/mk=344/se=23394/odds_api
/bt=1/bm=SN/mk=344/se=23394/odds_api
/bt=1/bm=BB/mk=344/se=23394/odds_api
/bt=1/bm=SF/mk=344/se=23394/odds_api
/bt=1/bm=XY/mk=344/se=23394/odds_api
```
I want to filter based on a list of bm values aka filter based on bm=SF,BB,MN.

To do this I created a filterList of MUST_PASS_ONE with 1 to many rowFilters (depending on how many values the user requests)

```
public ResultScanner scan(String id , List<String> bms) throws BigTableGetException {
    try{
        Table table = connection.getTable(TableName.valueOf(this.tableName));
        Scan scan = new Scan();
        scan.addFamily(Bytes.toBytes("odds_api"));
        FilterList mainFilterList = new FilterList(FilterList.Operator.MUST_PASS_ONE);

        bms.stream()
                .forEach(bm -> {
                    mainFilterList.addFilter(new RowFilter(CompareOp.EQUAL, new RegexStringComparator("/bt="+id+"/bm="+bm+".*")));

                });
        System.out.println("this is the filter list " + mainFilterList.toString());

        scan.setFilter(mainFilterList);
        return table.getScanner(scan);
    }catch (IOException ex){
        throw new BigTableGetException("Failed to get rows in BigTable", ex);
    }
}
```
(I know -- pointless stream for a forEach!)

This works fine when only one bm is specified, print statement:

`this is the filter list FilterList OR (1/1): [RowFilter (EQUAL, /bt=1/bm=B4.*)]
`
however if more than one is specified then it returns everything, print statement:

`this is the filter list FilterList OR (2/2): [RowFilter (EQUAL, /bt=1/bm=B4.*), RowFilter (EQUAL, /bt=1/bm=PP.*)]`
In fact, if I enter two or more 'incorrect' bm values it still returns everything!

I have also tried to move the bt=? filter out to a separate MUST_PASS_ALL filter and then have another list of row filters for bm=?

`this is the filter list FilterList AND (2/2): [FilterList AND (1/1): [RowFilter (EQUAL, .*bt=1)], FilterList OR (2/2): [RowFilter (EQUAL, .*/bm=B4.*), RowFilter (EQUAL, .*/bm=PP.*)]]`
Same problems.

hbase versions:

```
<dependency>
    <groupId>com.google.cloud.bigtable</groupId>
    <artifactId>bigtable-hbase-1.x</artifactId>
    <version>1.4.0</version>
</dependency>

<dependency>
    <groupId>com.google.cloud.bigtable</groupId>
    <artifactId>bigtable-hbase-1.x-hadoop</artifactId>
    <version>1.4.0</version>
</dependency>
```

### PR DESCRIPTION
**Pull request by rahulKQL**
Fixes #2008

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 1]
```diff
@@ -2118,6 +2118,43 @@ public void testFuzzyWithIntKeys() throws Exception {
...
+            "/firstKey=5/secKey=SET/thirdKey=777",
+            "/firstKey=11/secKey=AA/thirdKey=888"
+        };
+
+    List<Put> puts = new ArrayList<>();
+    byte[] qualA = dataHelper.randomData("test-regex");
+    for (int i = 0; i < rowKeys.length; i++) {
+      String indexStr = String.valueOf(i);
+      puts.add(
+          new Put(rowKeys[i].getBytes()).addColumn(COLUMN_FAMILY, qualA, Bytes.toBytes(indexStr)));
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Please create a single random byte string to put before these row keys.  This test might be run more than once.

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 2]
```diff
@@ -2118,6 +2118,43 @@ public void testFuzzyWithIntKeys() throws Exception {
...
+    }
+    table.put(puts);
+
+    // Expected rows should be sorted.
+    int[] expected = { 5, 4 };
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: shouldn't this be `{4, 5}` ?

Comment (rahulKQL) [reply bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: The test dataset I created was not sorted So returned output is in sorted order.
I would change the order of test data as it may create confusion.

Comment (sduskis) [reply bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: oh... I see.  Thanks for the clarification.

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java (hunk 1 above)
Comment (rahulKQL) [reply bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Thanks for the feedback, I have added a random Prefix to rows.

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 3]
```diff
@@ -2180,6 +2218,23 @@ protected Table addDataForTesting(String rowKeyPrefix, byte[] qualA)
     return table;
   }
 
+  private void assertRowKeysWithRegex(Table table, String[] rowRegEx,
+      String rowPrefix, String[] rowKeys, int[] expected) throws IOException {
+    FilterList filtersList = new FilterList(FilterList.Operator.MUST_PASS_ONE);
+    for (String con : rowRegEx) {
+      filtersList.addFilter(new RowFilter(CompareOp.EQUAL, new RegexStringComparator(con)));
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Shouldn't this be `new RegexStringComparator(rowPrefix + con)`?

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 4]
```diff
@@ -2180,6 +2223,24 @@ protected Table addDataForTesting(String rowKeyPrefix, byte[] qualA)
...
+    }
+    Scan scan = new Scan();
+    scan.setFilter(filtersList);
+    try (ResultScanner scanner = table.getScanner(scan)) {
+      Result[] results = scanner.next(10);
+      for (int i = 0; i < results.length; i++) {
+        Assert.assertArrayEquals(results[i].getRow(),
+            Bytes.toBytes(rowPrefix + rowKeys[expected[i]]));
+      }
+    }
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: please add another test to make sure that the `scanner.next()` is empty.

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 5]
```diff
@@ -2180,6 +2223,24 @@ protected Table addDataForTesting(String rowKeyPrefix, byte[] qualA)
...
+      String rowPrefix, String[] rowKeys, int[] expected) throws IOException {
+    FilterList filtersList = new FilterList(FilterList.Operator.MUST_PASS_ONE);
+    for (String condition : rowRegEx) {
+      filtersList.addFilter(new RowFilter(CompareOp.EQUAL,
+          new RegexStringComparator(rowPrefix + condition)));
+    }
+    Scan scan = new Scan();
+    scan.setFilter(filtersList);
+    try (ResultScanner scanner = table.getScanner(scan)) {
+      Result[] results = scanner.next(10);
```
Comment (sduskis) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: `scanner.next(rowKeys.length)` might be better than `scanner.next(10)`

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java (hunk 4 above)
Comment (rahulKQL) [reply bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Thanks for the comment, Added a check for the scanner.next().

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java (hunk 5 above)
Comment (rahulKQL) [reply bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java]: Thanks for the suggestion, Address the same.

**Comment by rahulKQL** [comment]
@sduskis 

I have address all the feedback, Please have a look.
